### ISSUE TITLE
Installing bindsnetQA

### ISSUE THREAD

**Issue by tehreemnaqvi** [Danielle-Schuman/bindsnetQA#1]
Hi,
Mam, I wanna ask how to install **bindsnetQA**?
I ready installed bindsnet and when I clone your repository,try to run your examples i.e **supervised.py** it gives me error that **bindsNetQA** not found then I reinstalled binsnet but got error.
In my current folder ,I copied your **bindsnetQA** but got error that this is not found. 
Thanks

**Comment by Danielle-Schuman** [comment]
Once you have downloaded or cloned the project, I think you should be able to install it by changing into the directory with the code and calling "pip install -e . ". But since you are probably the first person (apart from myself) who wants to use the code, I honestly am not sure if that will work and would not know what to do if it does not (I'm relatively new to developing python software and using GitHub).

Also, I have to warn you: This is still an ongoing project of mine, and I use a different way of calculating the execution of the spiking neural network. Thus, I am still unsure that it learns as well as the BindsNET-version, but what I do know is that it runs about 300 times slower (which is why I recommend using smaller parameters (like 10 or 20) for the number of neurons, the time, n_train and the update_interval) and it has some printouts which will probably be pretty meaningless to you (if you just want to try out how my code saves the plots, you can safely ignore those, though). Also, my code is highly tailored to supervised_mnist.py , so the other examples in the code will probably not work anymore.
